### ISSUE TITLE
captureOutput:didOuputSampleBuffer:fromConnection: not always being called on 64-bit devices

### ISSUE THREAD

**Issue by jrmsklar** [piemonte/PBJVision#109]
While running on a 64-bit device, we've discovered that  `-[PBJVision captureOutput:didOuputSampleBuffer:fromConnection:]` is not always called.

In our app, by default, we always have the camera mode set to `PBJCameraModePhoto`. When the user goes to record a video, we change the camera mode to `PBJCameraModeVideo`. When the user is done recording a video, we reset the camera mode back to `PBJCameraModePhoto` to restore its default state. If the user quickly goes to record a video again, then the delegate method mentioned previously (`-[PBJVision captureOutput:didOuputSampleBuffer:fromConnection:]`) is not called.

The way we came across this was by discovering that in this specific scenario, the `PBJMediaWriter`'s `_assetWriter` had a status of `AVAssetWriterStatusUnknown` inside the method `-[PBJMediaWriter finishWritingWithCompletionHandler:]`. Further, we realized that the `_assetWriter` did not have any inputs. We realized both of these issues were because the method that sets up the inputs  (`-[PBJVision captureOutput:didOuputSampleBuffer:fromConnection:]`) was not being called the second time recording a video.

We noticed that this issue does ***not*** occur when delaying several seconds between stopping recording, and beginning to record video again; and does ***not*** occur on 32-bit devices. We verified this by testing on an iPhone 5, iPod Touch (5th gen), iPhone 5S, and iPad Air.

**Comment by Alak** [comment]
Hey,

I try to use PBJVision 0.4.2 and i've same kind of issue (tested with iPhone 5c and iPhone 6) : 
I try to record a video but some delegate are not called because :
PBJMediaWriter's _assetWriter had a status of AVAssetWriterStatusUnknown inside the method -[PBJMediaWriter finishWritingWithCompletionHandler:]

**Comment by piemonte** [comment]
i believe this has been fixed, please let me know otherwise

**Comment by WANGNEWMAN** [comment]
Hey @jrmsklar. iOS 8.4 iphone 5c and ipad issue？

**Comment by jrmsklar** [comment]
Hey @WANGNEWMAN, iPhone 5C has Apple's A6 chip, which is 32-bit, thus this issue should not be happening on that device.

As for the iPad, it depends on the model that you're using. If it is a 32-bit device, this issue should not be happening, however, if it is a 64-bit device, then this issue can happen if it has not yet been fixed.

**Comment by WANGNEWMAN** [comment]
@jrmsklar the problem is iOS 8.4 thank you verry much
