### ISSUE TITLE
Why is PBJVision a singleton?

### ISSUE THREAD

**Issue by jodonnell** [piemonte/PBJVision#111]
Hello,

I have two problems that lead to my question:
When I record a second video the preview layer that comes up shows a still from the last video i have taken.

Occasionally, when i try record a video (I think its always after one succesfull but not sure) it looks like it is recording but when I finish the recording it has an error.  The one time I observed this with the device hooked up to Xcode I traced it to an AVAssetWriterStatusUnknown error.  The app must be restarted to be able to record a video again.

Creating a new PBJVision everytime my view is loaded fixes the first problem and I am hoping will fix the second (maybe not fix but i am hoping it won't require an app restart which is not nearly as obvious to a user as trying again).  I am not sure if there is a good reason the singleton accessor exists or if its just for convenience.

Thanks!
Jacob

**Comment by holahyunsik** [comment]
Above mentioned second issue does not only happen when the recording is stopped and then started very quickly in short time period. It happens every time.
