### ISSUE TITLE
Best practice to cancel capture

### ISSUE THREAD

**Issue by takusen** [piemonte/PBJVision#117]
Hi,

First of all, thanks for your work, this camera component is absolutely great.

I'd like to ask you if there is a good method to "cancel" a capture (i.e. removing all the segments that has been recorded during a record session to begin a new record).

If there is not such a good method to do so, I'll repost this ticket as an enhancement request.

Thanks by advance for your answer.

Taku

**Comment by panabee** [comment]
@takusen @packatino @CristianoCastroNabia **vision.capturedVideoSeconds** consistently returned negative values for us, but **videoDictionary[PBJVisionVideoCapturedDurationKey]** seems to return the correct value for the video duration. Thanks @piemonte for creating such an awesome library!
