### ISSUE TITLE
update delegate methods to allow frame processing

### ISSUE THREAD

**Issue by jaeheeko** [piemonte/PBJVision#151]
Hi. I really like using PBJVision. Its implementation is very neat and easy to use.

I'm trying to add some features in my project (including live filter on preview, capturing photo while recording a video, etc), but it seems to be difficult to add such features with PBJVision since the core processing part is all hidden in the .m file. 

I'd like to subclass PBJVision class and override captureOuput:didOutputSampleBuffer:fromConnection which is currently not accessible with super since its protocol is declared in PBJVision.m file. 
Any suggestions for this problem?

Thanks in advance!

**Comment by oligriffiths** [comment]
Did this go anywhere? Is it possible to apply filters to PBJVision output?
