### ISSUE TITLE
Set to specific video resolution

### ISSUE THREAD

**Issue by vash88** [piemonte/PBJVision#169]
I'm having trouble trying to set the resolution to 320x568 for iPhone 5 with decent compression. I want the preview to fit the screen too (similar to the native camera app).

This is what I currently have, the output size is 720x1280 and the compression is too much.

```
_previewView = [[UIView alloc] initWithFrame:CGRectZero];
_previewView.backgroundColor = [UIColor blackColor];
CGRect previewFrame = self.view.frame;
_previewView.frame = previewFrame;
_previewLayer = [[PBJVision sharedInstance] previewLayer];
_previewLayer.frame = _previewView.bounds;
_previewLayer.videoGravity = AVLayerVideoGravityResizeAspectFill;
[_previewView.layer addSublayer:_previewLayer];


vision.captureSessionPreset = AVCaptureSessionPresetHigh;
vision.additionalCompressionProperties = @{AVVideoProfileLevelKey : AVVideoProfileLevelH264Main31};
vision.outputFormat = PBJOutputFormatPreset;
```

**Comment by drwjf** [comment]
hi, dear @piemonte, Many thanks for great library.

How can I set the resolution to 320*240?  I try to use set videoBitRate to PBJVideoBitRate640x480/4 and set outputFormat to PBJOutputFormatPreset. But the result file resolution is 480*360. 

Best Regards,
