### ISSUE TITLE
better support for audioCaptureEnabled = NO

### ISSUE THREAD

**Issue by neilspenz** [piemonte/PBJVision#178]
Hey,
i'm using PBJVision for a while now and i have a problem
i think it's a bug...

i wanna disable the audio for the video capture.
ive done it by [vision setAudioCaptureEnabled:NO];
and indeed the output video is without audio,
the PROBLEM is that i'm only getting the first part of the video
by that i mean that the video was recorded by TAPS, every tap recording another part of the video

thanks in advance...

**Comment by itsmeichigo** [comment]
The same thing happens if you enable audio capture but turn off permission for microphone. This has got me insane for days now.

**Comment by dekeract** [comment]
Hi! I also notice this bug.
In "pauseVideoCapture" method vision sets "_flags.paused" and "_flags.interrupted" to YES.
In "resumeVideoCapture" it sets only "_flags.paused" to NO.

Problem was in method "captureOutput:(AVCaptureOutput *)captureOutput didOutputSampleBuffer:(CMSampleBufferRef)sampleBuffer fromConnection:(AVCaptureConnection *)connection" in this part of code:
```obj-c code
// calculate the length of the interruption and store the offsets
    if (_flags.interrupted) {
        if (isVideo) {
            CFRelease(sampleBuffer);
            return;
        }
        
        // calculate the appropriate time offset
        if (CMTIME_IS_VALID(currentTimestamp) && CMTIME_IS_VALID(_mediaWriter.audioTimestamp)) {
            if (CMTIME_IS_VALID(_timeOffset)) {
                currentTimestamp = CMTimeSubtract(currentTimestamp, _timeOffset);
            }
            
            CMTime offset = CMTimeSubtract(currentTimestamp, _mediaWriter.audioTimestamp);
            _timeOffset = CMTIME_IS_INVALID(_timeOffset) ? offset : CMTimeAdd(_timeOffset, offset);
            DLog(@"new calculated offset %f valid (%d)", CMTimeGetSeconds(_timeOffset), CMTIME_IS_VALID(_timeOffset));
        }
        _flags.interrupted = NO;
    }
```
"_flags.interrupted" is YES and "isVideo" always YES, because we don't receive audio samples - so "sampleBuffer" is always released. So after pause vision doesn't white video samples to file.

My fix for this was following:
```obj-c code
// calculate the length of the interruption and store the offsets
    if (_flags.interrupted) {
        if (isVideo && _flags.audioCaptureEnabled) {
            CFRelease(sampleBuffer);
            return;
        }
        
        if (!_flags.audioCaptureEnabled && CMTIME_COMPARE_INLINE(currentTimestamp, ==, _mediaWriter.videoTimestamp)) {
            CFRelease(sampleBuffer);
            return;
        }
        
        CMTime timestamp = (_flags.audioCaptureEnabled == YES) ? _mediaWriter.audioTimestamp : _mediaWriter.videoTimestamp;
        
        // calculate the appropriate time offset
        if (CMTIME_IS_VALID(currentTimestamp) && CMTIME_IS_VALID(timestamp)) {
            if (CMTIME_IS_VALID(_timeOffset)) {
                currentTimestamp = CMTimeSubtract(currentTimestamp, _timeOffset);
            }
            
            CMTime offset = CMTimeSubtract(currentTimestamp, timestamp);
            _timeOffset = CMTIME_IS_INVALID(_timeOffset) ? offset : CMTimeAdd(_timeOffset, offset);
            DLog(@"new calculated offset %f valid (%d)", CMTimeGetSeconds(_timeOffset), CMTIME_IS_VALID(_timeOffset));
        }
        _flags.interrupted = NO;
    }
```

I really love this library, it's great. @piemonte thanks a lot for it.

P.S. I don't know how to use markdown, so please forgive me if code will be unreadable.

**Comment by piemonte** [comment]
@dekeract thanks for the feedback and kind words! will look into a patch.

**Comment by dekeract** [comment]
After this changes I start to receive error sometimes that video file is corrupted because there are two samples with same time.

So I added 
```

if (CMTIME_COMPARE_INLINE(timestamp, ==, _videoTimestamp)) {
                    return;
                }

```

after this line - _assetWriterVideoInput.readyForMoreMediaData

**Comment by NikolaySohryakov** [comment]
@piemonte any update on this? Is there any stable fix available?

**Comment by ANTARESXXI** [comment]
Any update on this? How can we turn audio capture on/off during recording?
