### ISSUE TITLE
Feature request: capture a frame from the live preview buffer

### ISSUE THREAD

**Issue by rromanchuk** [piemonte/PBJVision#183]
Hey @piemonte I have a use case where i need to grab a frame from the live preview buffer in order to do some animation that doesn't require changing PBJVision modes. For example, lets say the user is in `PBJCameraModePhoto` and the user performs a gesture that requires immediate feedback/animation, in order to make animation smooth i basically need a freeze frame as a `UIImage` of the preview to make the animation fluid. 

I hacked my way into the project to get this working on my own fork, but i was wondering if you had any suggestions on how to clean this up, or if there is an easier route to take. 
https://github.com/rromanchuk/PBJVision/pull/3/files

**Comment by piemonte** [comment]
hey friends, i started to add some of this functionality in `0.4.0`

commit badecb000968249f933be76265a0da6f2b1b41e4
Author: patrick piemonte <patrick.piemonte@lastguide.com>
Date:   Tue Dec 23 22:42:39 2014 -0800

    PBJVision, add some initial code for photo capture during video recording, currently not exposed

need to pull in more changes from :

https://github.com/rromanchuk/PBJVision/pull/3/files
https://github.com/piemonte/PBJVision/pull/197

i'm using core image but i think rromanchuk's changes are a little better.

**Comment by krusek** [comment]
@piemonte when I call `captureVideoFrameAsPhoto` it freezes the preview layer.

**Comment by piemonte** [comment]
@krusek thanks, the feature hasn't been fully completed, feel free to submit a pull request if interested.

**Comment by benlachman** [comment]
Not sure if this PR is useful, but it's what I'm using for an OpenCV based scanner app.

**Comment by piemonte** [comment]
@benlachman thanks for the note. you might find the discussion here useful too:

https://github.com/medvedNick/PBJVision/commit/bdec195b1695f111aa1e461bb0f7d733da8ad35d#comments

**Comment by oligriffiths** [comment]
is there any status on this?

**Comment by piemonte** [comment]
this is actually in the latest release but untested. exposed with a category capturePhotoFromVideoFrame. The output is handled with the same photo delegate callback.

**Comment by piemonte** [comment]
feel free to contribute as no one is actively working on it.

**Comment by rromanchuk** [comment]
I can come back to this very soon

**Comment by mitchellporter** [comment]
>this is actually in the latest release but untested. exposed with a category capturePhotoFromVideoFrame. The output is handled with the same photo delegate callback.

@piemonte I can't seem to find the capturePhotoFromVideoFrame method. I've searched my pod files as well as here on GitHub.

Am I missing something?

**Comment by krusek** [comment]
you want the private method `captureVideoFrameAsPhoto`. When the thumbnail is ready it calls the delegate method `- (void)vision:(PBJVision *)vision capturedPhoto:(NSDictionary *)photoDict error:(NSError *)error`.

**Comment by rromanchuk** [comment]
@krusek is right here, @piemonte definitely merged this in, but has not publically exposed this yet. I'm using this in a fork (the pull request i sent), which i slapped in for my own needs but agree it's not really ready to be officially exposed yet. I'm a horrible person and keep saying i will spend time on this but haven't. For now I can water my fork with master where this is directly exposed if you need it working "now".  I haven't looked at how @piemonte moved this into master yet, since it wasn't a direct pull, so i can't advise you how to use it until I sit down with https://github.com/piemonte/PBJVision/commit/badecb000968249f933be76265a0da6f2b1b41e4 and take a look at it. 

I'm just curious, for the people who want this feature, why do you want it? I needed it for ` AVCapture` limitations as discussed in #231 but i'm curious to how y'all are trying to use it.

**Comment by krusek** [comment]
In my app [Rover](https://itunes.apple.com/us/app/rover-dog-lovers-for-hire/id547320928?mt=8) I'm grabbing thumbnails every second or so and showing a strip of thumbnails while recording.

**Comment by oligriffiths** [comment]
I'm using it for a snapchat style video/image capture view.

**Comment by rromanchuk** [comment]
Cool, yeah @oligriffiths same here, and i assume you are using video framed because actual mode switches are a pain in the ass?

**Comment by oligriffiths** [comment]
@rromanchuk Yup, it's a bitch. The one thing I have run into however, is triggering a full brightness flash when capturing the video frame. Manually turning on the flash/torch doesn't produce the super bright "photo" flash that you get if you're in photo mode. Any ideas?

**Comment by rromanchuk** [comment]
Opps, sorry didn't realize you opened that ticket, makes sense now.  What preset are you currently using? `AVCaptureSessionPresetHigh`? 

@oligriffiths it's really hard :(  `AVCaptureSessionPresetPhoto` with `captureStillImageAsynchronouslyFromConnection(_:completionHandler:)` is actually doing a lot of things in the background. When we use a frame from the buffer, we get none of this. If you're snapchat you probably have a couple engineers working on perfecting this capture fulltime. I have yet to see a single thing on the market that takes `AVCaptureSessionPresetPhoto` native resolution photos and a video without a toggled mode switch. (apple camera, instagram, etc......)  If you find any one out there doing it let me know. 

I have a  `AVCaptureSessionPresetPhoto` -> `AVCaptureSessionPresetHigh` long press mode switch, but it's anything but "smooth"

**Comment by oligriffiths** [comment]
@rromanchuk I don't need full resolution photos, video quality is fine, and it's working nice and smoothly. The issue is getting the flash to flash a full brightness for a "photo", essentially, how do you trigger a full brightness flash in code?

**Comment by rromanchuk** [comment]
@oligriffiths you're a lucky SOB :P  I think the bigger problem is that the flash, with photos, uses very precise clock time to align the frame that is captured with the flash event. Haven't spent much time here because my use case requires high quality photos so I had to move away from the live buffer capture

**Comment by mikekhristo** [comment]
Anyone happen to have an update on this?
