### ISSUE TITLE
Strange KVO exception "currentDevice"

### ISSUE THREAD

**Issue by jpswensen** [piemonte/PBJVision#189]
I am getting the following exception at unpredictable times. The app works 99.9% of the time, but am occasionally getting a KVO exception. The source is the portion of _sessionStarted in which the _currentDevice is updated and the KVO change notification is triggered:
                [self willChangeValueForKey:@"currentDevice"];
                _currentDevice = device;
                [self didChangeValueForKey:@"currentDevice"];

The exception claims that KVO is not set up right
"Fatal Exception: NSInternalInconsistencyException
Cannot update for observer <PBJVision 0x1d056f20> for the key path "currentDevice.torchMode" from <PBJVision 0x1d056f20>, most likely because the value for the key "currentDevice" has changed without an appropriate KVO notification being sent. Check the KVO-compliance of the PBJVision class."

I have been trying to debug this, but it happens so infrequently that I am not sure how to make it happen and only have Crashlytics logs that the crash occurred.

**Comment by IPv6** [comment]
same situation here, it happens from time to time... may be _currentDevice = nil; in destroyCamera should be wrapped in KVO calls too?

**Comment by dhanushram** [comment]
++1 has anyone figured this out yet?

**Comment by rksaraf** [comment]
Is there a known fix for this?

**Comment by dustturtle** [comment]
@IPv6 what is your solution for #220 ? Thanks
