### ISSUE TITLE
Strange red audio recording flash when app is in foreground

### ISSUE THREAD

**Issue by rromanchuk** [piemonte/PBJVision#193]
Not sure if this is an ios8 issue, `PBJVision` issue, or something else, but anyone else experiencing this? 

https://stackoverflow.com/questions/22347414/red-status-bar-shown-while-switching-camera-using-avfoundation

http://stackoverflow.com/questions/26055717/red-audio-recording-status-bar-flashes-while-app-in-foreground

**Comment by mitchellporter** [comment]
Any progress made on this? I'm having the same issue. Once the red bar appears, it's always visible no matter how many times I rerun the app.

**Comment by mitchellporter** [comment]
Based off of the answers that Ryan linked to, I ended up adding thos to dealloc in PBJVision.m:

    // Remove input
    [_captureSession removeInput:_currentInput];

Hopefully this works. Unfortunately, this issue happens sporadically for me so I'll have to wait for a while before I can confirm whether this works or not.

**Comment by mitchellporter** [comment]
The "solution" I posted above doesn't seem to work.
