### ISSUE TITLE
add better support for suspend/resume video recording (file appending)

### ISSUE THREAD

**Issue by piemonte** [piemonte/PBJVision#2]
add better support for suspend/resume while recording

**Comment by alonahar** [comment]
Hi @piemonte, is there any progress with any of these issues? 
Moving to background / receiving a call while recording turns out to be a common behaviour.
Is there any workaround to not loose the recording in these cases?

Thanks a lot.

**Comment by piemonte** [comment]
hi there. none to report by me.

**Comment by piemonte** [comment]
hey everyone, i started a swift version of this project that is properly handling suspend/resume:

http://github.com/nextlevel/nextlevel

just posted it a few days ago, so some functionality needs a little love.
