### ISSUE TITLE
Delay in start capture

### ISSUE THREAD

**Issue by JiriTrecak** [piemonte/PBJVision#207]
I am writing vine-like application and I already have everything working except one small issue - when you start capture and then end it really quick (hold-to-record functionality, 0.1 - 1.0 second hold at the beginning), it will leave capture in some state that is mix of both, and then the singleton does not work at all. 

What I tried and had most success is to actually preload the capture by starting it through code, then immediately after visionDidStartVideoCapture: is called I pause it and then I only use pause / resume to continue. This is the closest I got to actually solving the problem, but it is still not what I call acceptable (sometimes it just does not pause for example, then there is a problem that there is one extra starting frame etc..).

Have anyone been experiencing the same issue?

**Comment by holahyunsik** [comment]
Hey @JiriTrecak  how'd you fix it?? I'm surprised this has been mentioned only once and closed.
