### ISSUE TITLE
Capture front camera photo is vertically flipped after being saved

### ISSUE THREAD

**Issue by dannyhertz** [piemonte/PBJVision#213]
I'm trying to write a photo to the photo album and my front facing photos are always vertically flipped (until it is slightly zoomed). A GIF to help:

![img_7551](https://cloud.githubusercontent.com/assets/407719/5520324/de547cec-8949-11e4-946e-511d01d88ce0.GIF)

I've tried saving the UIImage with the orientation set to image.imageOrientation like so:

```
[assetsLibrary writeImageToSavedPhotosAlbum:currentImage.CGImage orientation:(ALAssetOrientation)currentImage.imageOrientation completionBlock:nil];
```

I've also tried to save the PBJVisionPhotoJPEGKey data with the PBJVisionPhotoMetadataKey dictionary and am getting the same results:

```
NSDictionary *currentMediaMetadata = currentMediaDict[PBJVisionPhotoMetadataKey];
NSData *currentMediaData = currentMediaDict[PBJVisionPhotoJPEGKey];

[assetsLibrary writeImageDataToSavedPhotosAlbum:currentMediaData metadata: currentMediaMetadata completionBlock:nil];
```

vision.cameraOrientation is set to 0 and vision.mirroringMode is set to PBJMirroringAuto at the time if that helps.

Any help would be appreciated!

**Comment by zipnadarien** [comment]
FWIW, in my app, I take the photo and combine it w/ another image and then save that new image to file. In this case, any image taken from the front camera is not flipped.

**Comment by piemonte** [comment]
at some point a bug got introduced where the orientation just isn't being set properly on the image, the camera default is 90 CCW (landscape left). so when that get's mirrored in it's vertical, it flips it upside-down. will try hunt it down where the orientation is getting reset. thanks for all the feedback.

**Comment by piemonte** [comment]
figured out the issue, patch in the works :+1:

**Comment by Enter91** [comment]
@piemonte Hi, did you find out what is causing this bug?

**Comment by Anders123fr** [comment]
This issue is still open, using the latest version 0.4.2.
Any news about a fix?

**Comment by lmick002** [comment]
@zipnadarien Do you mind sharing your solution?

**Comment by zipnadarien** [comment]
Larry M - been a long time since I worked on that code, give me a few weeks
and I'll check what I did and respond.

**Comment by lmick002** [comment]
Thanks @zipnadarien

**Comment by zipnadarien** [comment]
It's been a year since I last worked on my app (slo-mo booth). As I mentioned in my post from Jan2015, when I grab a photo, I insert it into another image. I'm creating a filmstrip of 4 photos in the final image and that's what I save. I reviewed my code for a bit today and don't see that I'm doing anything different or did any kind of mod to the original PBJVision code. So....either I did a mod that I don't remember (didn't make any comments in the code or my repo) or I didn't do anything cause I don't see the bug for how I'm using the photo feature.

**Comment by harirao002** [comment]
I've the same problem. Any updates?

**Comment by harirao002** [comment]
@piemonte : Did you find any solution for this issue?

**Comment by harirao002** [comment]
Try this one :

if (objPhoto.imageOrientation == UIImageOrientationLeftMirrored) {
        
        imageToDisplay =
        [UIImage imageWithCGImage:[objPhoto CGImage]
                            scale:[objPhoto scale]
                      orientation: UIImageOrientationRight];
    }

My issue is fixed by using above code.
