### ISSUE TITLE
How can I capture slow motion video

### ISSUE THREAD

**Issue by pkadetiloye** [piemonte/PBJVision#217]
I just found your library, am able to do a video capture but I would like to know how I
can use it to make a slow motion video.

Thanks

**Comment by piemonte** [comment]
@pkadetiloye thanks for your interest in the project and support. i've been wanting to add in examples for slow motion capture adjustment but there is also a bug with this feature.

dup
:paperclip: https://github.com/piemonte/PBJVision/issues/25
:paperclip: https://github.com/piemonte/PBJVision/issues/127
