### ISSUE TITLE
Crash in finishWritingWithCompletionHandler

### ISSUE THREAD

**Issue by bwhiteley** [piemonte/PBJVision#218]
I'm seeing frequent crashes after capturing multiple video segments. 

Crash at:
PBJMediaWriter.m:308: [_assetWriter finishWritingWithCompletionHandler:handler];

Here is the last thing in the log:
VISION: cancel video capture
**\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '**\* -[AVAssetWriter finishWritingWithCompletionHandler:] Cannot call method when status is 2'

**Comment by piemonte** [comment]
@bwhiteley thanks for reporting, other folks have encountered this issue too.

it occurs when you're trying to start writing again before the media writer hasn't completely finished, which can easily happen if start and cancel is being called from different threads.

**Comment by tarslangil** [comment]
@piemonte This crash still happening in my application.Is there a bug fix for this?

I'm not using any thread.Just opening PBJViewController and closing it with cancelVideoCapture method with a button using a selector.

**Comment by aiyub007** [comment]
Same Problem

**Comment by piemonte** [comment]
Hey friends, thanks for the feedback. There's a bunch of logic I'd like to rework in PBJVision but I don't have the time right now. In the meantime, I'd like to recommend the Swift project I pulled together which handles segment recording more gracefully:

🔨 http://github.com/NextLevel/NextLevel
