### ISSUE TITLE
NSInternalInconsistencyException in [DVCameraViewController capture]

### ISSUE THREAD

**Issue by IPv6** [piemonte/PBJVision#220]
Sometimes image capture breaks with NSInternalInconsistencyException

---
Info: *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '*** -[AVCaptureStillImageOutput captureStillImageAsynchronouslyFromConnection:completionHandler:] - inconsistent state.'

1	CoreFoundation	__exceptionPreprocess + 132
2	libobjc.A.dylib	objc_exception_throw + 56
3	AVFoundation	-[AVCaptureStillImageOutput captureStillImageAsynchronouslyFromConnection:completionHandler:] + 416
4	PhotoChat	-[PBJVision capturePhoto] (PBJVision.m:1619)
5	PhotoChat	-[DVCameraViewController capture:] (DVCameraViewController.m:389)
6	UIKit	-[UIApplication sendAction:to:from:forEvent:] + 92

**Comment by piemonte** [comment]
@IPv6 ! nice handle. thanks for letting me know. we've got a bug tracking this currently.

:paperclip: https://github.com/piemonte/PBJVision/issues/189

**Comment by cajic-xeetech** [comment]
Are there any news on this?

**Comment by dustturtle** [comment]
Why this issue closed? Is it solved? How?
