### ISSUE TITLE
Photo cropping?

### ISSUE THREAD

**Issue by justinmakaila** [piemonte/PBJVision#221]
Is there a way to configure the output format of the captured photos? I'd like to capture them in a square, with the same frame as the preview layer, but I keep getting full images.

**Comment by piemonte** [comment]
hey @justinmakaila. the output property currently supports video, never added in the photo support but i do have a bug for it. will look into it for you.

**Comment by piemonte** [comment]
:paperclip: https://github.com/piemonte/PBJVision/issues/153
