### ISSUE TITLE
Is there anyway to support delete last video snippet？

### ISSUE THREAD

**Issue by JGINGIT** [piemonte/PBJVision#222]
Like Instagram long press on shoot button open a new video snippet, so you can delete last one or all of them. When you done, it compose all the snippet to a video.

**Comment by piemonte** [comment]
hey @JGINGIT currently, that feature isn't supported but there's an issue tracking the feature. i've had several folks reach out about it being an important addition might try do it over one weekend.

:paperclip: https://github.com/piemonte/PBJVision/issues/9
:paperclip: https://github.com/piemonte/PBJVision/issues/2
