### ISSUE TITLE
Photo Capture becomes slow after capturing a video

### ISSUE THREAD

**Issue by narekgevorgyan** [piemonte/PBJVision#223]
Hi there,

First of all thanks a lot for a great library. I use it for one of my projects.

I'm using the same PBJVision instance (of course the same its sharedInstance :)) for taking photos or videos  with changing the camera mode using  setCameraMode function.

Tho I noticed the following error. Initial state for the PBJVision instance is PBJCameraModePhoto. Taking photos is near to being an instance and is very fast. But after changing camera mode to PBJCameraModeVideo, successfully taking a video and changing back to PBJCameraModePhoto the photo capture seems to take some time (around 1-1.5 seconds). Any ideas?

**Comment by piemonte** [comment]
hey @narekgevorgyan have you noticed differences in memory usage or are you holding pointers to any of the resulting output media too long?

**Comment by narekgevorgyan** [comment]
Hi @piemonte ,

I'm just loading the resulting Video to a AVPlayer and then remove the AVPlayer instance from the memory before taking the next photo.
So you think the memory usage can affect the speed of taking a photo?

**Comment by narekgevorgyan** [comment]
One thing I noticed. After calling capturePhoto it takes around 0.5 seconds for the willCapturePhoto function to be called and that is the main difference between this and a normal scenario when willCapturePhoto is being called after 10 milliseconds

**Comment by narekgevorgyan** [comment]
Hey @piemonte ,

No I'm removing the video output pointers (AVPlayer,AVPlayer item) before capture a new photo. You think that can be a memory issue? The strange thing is that after video, photo taking speed is becoming constant 0.5 seconds no matter of the lenght of the video.

**Comment by piemonte** [comment]
Hey @narekgevorgyan thanks for the interest in the project btw. so i don't have enough information to know. if you can reproduce the behavior in the sample app or have some detailed specifics on the memory use between those two states, that'd be helpful.

**Comment by narekgevorgyan** [comment]
Thanks @piemonte ,

I haven't done anything extraordinar. Just changed your sample project with adding a button for changing the camera mode.

What I noticed as well is that the front facing camera photo capture speed is instant no matter if the video taken before or not.

**Comment by piemonte** [comment]
by adjusting the photo output preset to be lower quality, you can increase the speed. by default PBJVision tries to capture the highest quality image from the rear camera. that's why front is also faster.
