### ISSUE TITLE
Force stop error (Crash error)

### ISSUE THREAD

**Issue by manisolutions14** [piemonte/PBJVision#224]
Hi friend,
        PBJvision not working when start to record in ios 6.1.6 (iPod 4th Gen), Please help me 

am waiting for reply.............

**Comment by piemonte** [comment]
@manisolutions14 hi, thanks for interest in the project. most folks use stackoverflow.com for general inquires and discussion.

it is always good to include backtraces or specific logs for problems you may encounter.

**Comment by manisolutions14** [comment]
Thnk piemonte......
