### ISSUE TITLE
Rewind when recording ?

### ISSUE THREAD

**Issue by mstzn** [piemonte/PBJVision#228]
Hi,
I'm using this repo in my application. But I've a problem with rewind video when recording.

Such as when 3rd second of video I want to rewind to 2 and record 3rd second again.
Override 3rd second. Like cutting.

Is this possible or how can I do this?

Thank you.

**Comment by piemonte** [comment]
hey @mstzn thanks for interest in the project. that functionality isn't supported now but will sometime this summer or in another project i've been working on.

:paperclip: https://github.com/piemonte/PBJVision/issues/2
