### ISSUE TITLE
maximumCaptureDuration not working when pausing/resuming

### ISSUE THREAD

**Issue by mitchellporter** [piemonte/PBJVision#229]
I've set ```maximumCaptureDuration``` to 5 seconds. If I long press and hold for 5 seconds, ```maximumCaptureDuration``` works and the video recording ends, but if I let go of my long press, then press again to keep recording, ```maximumCaptureDuration``` will not work on it's own and you can keep recording for as long as you want.

**Comment by piemonte** [comment]
hey @mitchellporter i'm unable to reproduce this with the sample project. are you always calling startVideoCapture following the maximumCaptureDuration "end"?

**Comment by mitchellporter** [comment]
@piemonte Sorry for the delay in reply! I'm unable to recreate this as well now that I've been further integrating PBJVision. Not sure what I was doing wrong before, but looks like this was a false bug.
