### ISSUE TITLE
Where you draw after this?

### ISSUE THREAD

**Issue by Khazmovsky** [piemonte/PBJVision#232]
[self _processSampleBuffer:bufferToWrite];
if find you didn't bind any thing(buffer/texture) to opengl, where do opengl draw to?

**Comment by piemonte** [comment]
hi @Khazmovsky 

everything is drawn to PBJVision's glContext here:
https://github.com/piemonte/PBJVision/blob/master/Source/PBJVision.h#L211
https://github.com/piemonte/PBJVision/blob/master/Source/PBJVision.m#L2556

the context is bound to a GLKView here:
https://github.com/piemonte/PBJVision/blob/master/Project/Vision/PBJViewController.m#L156-L164
