### ISSUE TITLE
Want to record device audio like Music player or Spotify player playing audio in video recording

### ISSUE THREAD

**Issue by harry225** [piemonte/PBJVision#233]
Is there any way using that can reacord device audio like Music player or Spotify player playing audio in video recording with mic sound?
Want to record both sound device(player) audio and mic audio like snapchat app.

**Comment by harry225** [comment]
Please provide some suggestion.

**Comment by viral105** [comment]
Did you found any solution ?

**Comment by viral105** [comment]
i updated following code in PBJVision.m in this method - (id)init

[[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayAndRecord
                                                  withOptions:AVAudioSessionCategoryOptionMixWithOthers
                                                        error:nil];
        
        NSError *error;
        
        [[AVAudioSession sharedInstance] setPreferredInputNumberOfChannels:2 error:&error];
        if(error)
        {
            NSLog(@"error doing outputaudioportoverride - %@", [error localizedDescription]);
        }
it is working for ios 7 but not working for ios 8.

Anyone having soultion for this problem ?
