### ISSUE TITLE
Cannot call method when status is 2

### ISSUE THREAD

**Issue by imclean** [piemonte/PBJVision#238]
Getting this all the time in 8.3

Seems you have some threading issues.

**Comment by imclean** [comment]
I find if I change your finish method to this it works:
- (void)finishWritingWithCompletionHandler:(void (^)(void))handler
{
    if (_assetWriter.status == AVAssetWriterStatusUnknown ||_assetWriter.status==AVAssetWriterStatusCompleted) {
        DLog(@"asset writer is in an unknown state, wasn't recording");
        return;
    }

    [_assetWriter finishWritingWithCompletionHandler:handler];
}

**Comment by piemonte** [comment]
commit 0b9f070226d09aa2e48511ed333f61aba045685d
Author: patrick piemonte <piemonte@alumni.cmu.edu>
Date:   Wed Apr 15 09:37:55 2015 -0700

    PBJMediaWriter, minor handling for when end capture is called multiple times

:v:
