### ISSUE TITLE
PBJVision used in Xcode 6.3 with swift 1.2 delegate method name conflicts with optional requirement  name

### ISSUE THREAD

**Issue by n8stowell82** [piemonte/PBJVision#239]
While this setup is probably not completely supported, I thought I would report an issue I am having with pbjvision while using it from swift 1.2 project

Objective-C method 'vision:capturedVideo:error:' provided by method 'vision(_:capturedVideo:error:)' conflicts with optional requirement method 'vision(_:capturedVideo:error:)' in protocol 'PBJVisionDelegate'

**Comment by piemonte** [comment]
thanks @n8stowell82 this has been reported and should be fixed on master

**Comment by piemonte** [comment]
:paperclip: https://github.com/piemonte/PBJVision/pull/236

**Comment by n8stowell82** [comment]
has this been updated so that cocoapods will pick it up?  I just did a pod update

**Comment by piemonte** [comment]
@n8stowell82 not yet, you can point the Podfile to head, will submit soon.

pod 'PBJVision', :head

**Comment by n8stowell82** [comment]
thank you so much!
