### ISSUE TITLE
Can we set up the export to produce M4V files instead of MP4

### ISSUE THREAD

**Issue by ivan-konov** [piemonte/PBJVision#241]
There is no such option or at last I did not find in the class and it's settings. I am ok of editing it myself you you can give me a clue so you do not rush another update.

Thanks in advance!

**Comment by piemonte** [comment]
hey @ivan-konov you're correct, there is no current option for that, but contributions are welcome.

**Comment by halpz** [comment]
they are identical types, just rename the file extension!
