### ISSUE TITLE
memory size  and resolution

### ISSUE THREAD

**Issue by ajay2c9** [piemonte/PBJVision#243]
Hai how can we reduce the memory size of the large image without loosing quality of the image i.e resolution of the image. i reduce the image by using UIImageJPEGRepresentation(squareimage, 0.6). image memory is reduced but the output image blur in iphone 5s  and iphone 6.If i take a image in the iphone 5s  the image is blur in iphone 6  and iphone 6plus.please suggested how to compress the image or video like without lossing  resolution like instagram

**Comment by piemonte** [comment]
hey @ajay2c9 please use stackoverflow.com for discussions. thanks for your interest in the project. :v:
