### ISSUE TITLE
Preview frozen but capture functioning.

### ISSUE THREAD

**Issue by benlachman** [piemonte/PBJVision#244]
Using a modified version of the view controller from the example project, when I transition to another view controller the preview freezes. Upon return to the view controller with the preview, the preview stays frozen. Capture happens as normal however.  I can't seem to get it unfrozen with an combination of startingPreview, removing/readding previewView, end/restartCapture. Am I missing something?

**Comment by piemonte** [comment]
hey @benlachman it could be bug where the preview layer isn't reconfigured properly or the connection isn't enabled. maybe check the previewLayer reference and `unfreezePreview`.

**Comment by benlachman** [comment]
I think this was an issue with the preview being disabled. I'll close this issue. Thanks!

**Comment by piemonte** [comment]
:+1:
