### ISSUE TITLE
Complete Example Project

### ISSUE THREAD

**Issue by geogerar** [piemonte/PBJVision#25]
Hello,
You have made an exellent work with PBJVISION.
You help all of us a lot!
But, I would like to kindly ask from you, If it is possible to have a more complete example project using all your features, e.g. Set flash on/off, set camera front/rear,
grab video/photo etc.
You will help all of us that happens to be start beginners with objective c  and IOS!
Thank you in advance.

George N. Gerardis

**Comment by piemonte** [comment]
@melvinwijenayaka thanks for the project interest. not sure what could be causing that but i do have a couple libraries on the way, which may be helpful to you.

**Comment by maheshkolagatla** [comment]
Can you provide PBJVision  in swift

**Comment by piemonte** [comment]
@maheshkolagatla that was the idea for https://github.com/NextLevel/NextLevel
