### ISSUE TITLE
BUG - stops recording when flips camera from front to back with AVCaptureSessionPresetHigh resolution

### ISSUE THREAD

**Issue by Skornos** [piemonte/PBJVision#251]
Hi,

if you flip the camera from the FRONT facing to the BACK the recording will last only about 1 second then didCaptureVideoSampleBuffer returns still the same number of capturedVideoSeconds. It is necessary to mention that you need to set 
vision.captureSessionPreset = AVCaptureSessionPresetHigh;

**Comment by piemonte** [comment]
@Skornos thanks for the tip. please submit a pull request if this would be helpful for others.
