### ISSUE TITLE
Mirroring Mode (PBJMirroringOff) fail when switch camera

### ISSUE THREAD

**Issue by tienphong923** [piemonte/PBJVision#255]
Hello.
I've just executed PBJVision sample project. When I set mirroringMode = PBJMirroringOff and cameraDevice = PBJCameraDeviceFront it return different results.

On function resetCapture, I've just changed:

``` objective-c
- (void)_resetCapture
{
...
// Changed: Set default camera is FRONT on first open app
if ([vision isCameraDeviceAvailable:PBJCameraDeviceFront]) {
        vision.cameraDevice = PBJCameraDeviceFront;
        //_flipButton.hidden = NO;
    } else {
        vision.cameraDevice = PBJCameraDeviceBack;
        //_flipButton.hidden = YES;
    }

// Add new this line: Turn off mirroring Mode 
vision.mirroringMode = PBJMirroringOff;
...
}
```

When I run sample project on first time app open, everything working well (it's working same as default camera on iOS device). After that, I switched camera front to back, and switch again from back to front, camera was shown preview with mirror image.
Image 1 : Fan was left; 
Image 2 : Fan was right (after switch camera)

![img_0958](https://cloud.githubusercontent.com/assets/4022885/7791517/ae7608d2-02cb-11e5-82d7-43ad422fbea4.PNG) ![img_0959](https://cloud.githubusercontent.com/assets/4022885/7791518/ae7d083a-02cb-11e5-9b7f-f3cab88ac232.PNG)

Please fix it soon, thank so much!

**Comment by piemonte** [comment]
thanks @tienphong923 someone will take a look

**Comment by mitchellporter** [comment]
I'm having problems with the mirroringMode as well with iOS 8 on an iPhone 6.

Very strange, but when I first tested this with PBJMirroringOn it worked with the front facing camera the very first time, and now I can't get it to work. I've cleaned the project, deleted the app, restarted Xcode, etc.

It works for the back facing camera but not the front facing camera.
