### ISSUE TITLE
Crash call delegate [didCaptureVideoSampleBuffer]

### ISSUE THREAD

**Issue by remirobert** [piemonte/PBJVision#260]
Hi, i got i crash with this delegate : 

I really need this call, this is essential for my application.
How can i fix it ?

```Objective-c
- (void)vision:(PBJVision *)vision didCaptureVideoSampleBuffer:(CMSampleBufferRef)sampleBuffer;
```

Thanks in advance.

**Comment by olivierlesnicki** [comment]
This is a duplicate of https://github.com/piemonte/PBJVision/issues/254

**Comment by remirobert** [comment]
Ok thanks. So what is your solution. Because I didn't find the solution there. And I don't want modify the code. This is a major bug.

**Comment by piemonte** [comment]
thanks for reporting, someone will take a look. yes, is a duplicate.
