### ISSUE TITLE
PBJVision returned video URL not working

### ISSUE THREAD

**Issue by ryanprinster** [piemonte/PBJVision#261]
I'm trying to use PBJVision to get the URL of a video then preview it on a separate part of the app. I'm passing along the URL created with this code:

- (void)vision:(PBJVision *)vision capturedVideo:(NSDictionary *)videoDict error:(NSError *)error{

    NSString *videoPathString = [videoDict objectForKey:PBJVisionVideoPathKey];
    NSURL *videoPathURL = [NSURL URLWithString:videoPathString];
    ...
}

eventually into this code as selectedMediaURL:

self.player = [[MPMoviePlayerController alloc] initWithContentURL:selectedMediaURL];
[self presentMoviePlayerViewControllerAnimated:self.player];
[self.player.view setFrame:CGRectMake(0, 0, 320, self.view.frame.size.height - 44)];
[self.view addSubview:self.player.view];
[self.player play];

However, the URL seems not to work. If I instead open the same video from the photos album using WSAssetPickerController, I get a different URL but it works. 

The URL I get looks something like this: /private/var/mobile/Containers/Data/Application/52A39C59-88A1-4C4F-896B-2D2BECBB0ACE/tmp/video_DCE2796D-992A-423A-9590-63CAB0F7CC67.mp4

However, when I load the same video from the saved photos album I get this URL which does work: assets-library://asset/asset.mp4?id=56E8F701-188C-44C8-B141-9BB7C623A7CC&ext=mp4

Any thoughts?

**Comment by mnmaraes** [comment]
Don't use:
`NSURL *videoPathURL = [NSURL URLWithString:videoPathString];`

use:
`NSURL *videoPathURL = [NSURL fileURLWithPath:videoPathString];`
instead.

**Comment by piemonte** [comment]
thanks @mnmaraes
