### ISSUE TITLE
Customizing video resolution

### ISSUE THREAD

**Issue by mitchellporter** [piemonte/PBJVision#265]
I'm trying to basically recreate some functionality that Vine offers. I am using the PBJVision demo project which has a preview layer of 320x320 when you are recording which is identical to Vine.

I wanted to customize the demo project to give me a final video file with a resolution of 540x540 though which would provide me with a video file that could be used both on the iPhone and on the web, so I went into the `PBJVision.m` file and changed the `AVVideoWidthKey` and `AVVideoHeightKey` keys:

``` Objective-C
NSDictionary *videoSettings = @{ AVVideoCodecKey : AVVideoCodecH264,
                                     AVVideoScalingModeKey : AVVideoScalingModeResizeAspectFill,
                                     AVVideoWidthKey : @(540),
                                     AVVideoHeightKey : @(540),
                                     AVVideoCompressionPropertiesKey : compressionSettings };
```

This works, but now I'm wondering about the default setup code that comes with the demo project:

``` Objective-C
vision.cameraMode = PBJCameraModeVideo;
 //vision.cameraMode = PBJCameraModePhoto; // PHOTO: uncomment to test photo capture
 vision.cameraOrientation = PBJCameraOrientationPortrait;
 vision.focusMode = PBJFocusModeContinuousAutoFocus;
 vision.outputFormat = PBJOutputFormatSquare;
 vision.videoRenderingEnabled = YES;
 vision.additionalCompressionProperties = @{AVVideoProfileLevelKey : AVVideoProfileLevelH264Baseline30}; // AVVideoProfileLevelKey requires specific captureSessionPreset
```

After customizing the resolution and recording a 2 minute video, the file comes out to about 30 MB which is too big.

So I customized the settings real quick and now I have this:

``` Objective-C
vision.cameraMode = PBJCameraModeVideo;
//vision.cameraMode = PBJCameraModePhoto; // PHOTO: uncomment to test photo capture
vision.cameraOrientation = PBJCameraOrientationPortrait;
vision.focusMode = PBJFocusModeContinuousAutoFocus;
vision.outputFormat = PBJOutputFormatSquare;
vision.videoRenderingEnabled = YES;
vision.videoBitRate = PBJVideoBitRate480x360;
vision.additionalCompressionProperties = @{AVVideoProfileLevelKey : AVVideoProfileLevelH264Baseline30}; // AVVideoProfileLevelKey requires specific captureSessionPreset
```

The file recorded with the customized settings comes out to around 11 MB which is perfect but there is a noticeable loss of quality, especially if there is movement while recording. For example, if I record my code in Xcode and move the camera a little, and then you watch the recording, the text gets very grainy while moving.

At this point I am trying to figure out how I can get the video file to be anywhere from 10 - 20 MB without a huge loss of quality. I'm willing to learn, but the problem is these video settings are a bit confusing.

I'm not sure if I need to change the `additionalCompressionProperties` property, if I should stop setting `videoRenderingEnabled`, etc.

There was another issue that touched on these same things which can be seen here: https://github.com/piemonte/PBJVision/issues/29

The project owner @piemonte offered some quick advice and sample code but he didn't really explain the math or formula you can use to customize the bit rate outside of the predefined presets included with the project.

Would love to get a discussion going on this as I'm sure I'm not the only one here who could both benefit from customizing the video resolution and learning to tweak the various settings based on that custom resolution.

Thanks.

**Comment by mitchellporter** [comment]
Update: I *think* that what I need to do is figure out a custom `videoBitRate` to match my custom resolution of `540x540`.

The problem is I don't know of the proper formula to come up with the bit rate value.

There is another closed issue here: https://github.com/piemonte/PBJVision/issues/22

And the very last comment is from the owner of the project @piemonte:

>@yury the bit rate comes from total number of pixels (video width x height) * (bits per pixel)

This doesn't make sense to me though because take for example the preset of `PBJVideoBitRate480x360` which is defined as:
```Objective-C
static CGFloat const PBJVideoBitRate480x360 = 87500 * 8;
```

That math for that would then be `(480x360) * (8.0)`, but `480x360` does not equal `87500`.

**Comment by piemonte** [comment]
@mitchellporter hey there, thanks for the inquiry. it has been some time since i looked at those calculations, i'll find a moment and get back to you on this. it should be well commented and maybe a helper method, to say the least. :+1:

**Comment by mitchellporter** [comment]
@piemonte Sounds great thanks man :+1:

**Comment by panabee** [comment]
Thanks for this awesome library, @piemonte! Just want to check in and see if there's any update on this issue ... thanks again!
