### ISSUE TITLE
Possible to use for live broadcasting ?

### ISSUE THREAD

**Issue by shubhank008** [piemonte/PBJVision#267]
Can the library be used for live streaming or rather broadcasting of videos ?  
I have used and played with the library a bit for normal video recording and such and instantly starred it, really great work done.  

But I was wondering, is it possible to get the video/audio stream to livestream the recording directly to a HLS/RTMP server ? I can work around the actual broadcasting implementation but can't find any clues on how to get the actual stream as only found the delegate for when video has finished recording.

**Comment by piemonte** [comment]
Hey @shubhank008 great inquiry. There's been a bunch of requests for this. I don't have an immediate answer for you but I'll use your bug to track anything in that area.

**Comment by olivierlesnicki** [comment]
You can use VideoCore for live streaming, works a charm! @shubhank008
