### ISSUE TITLE
vision:(PBJVision *)vision capturedPhoto not working

### ISSUE THREAD

**Issue by shubhank008** [piemonte/PBJVision#268]
Using latest cocoapod install and trying the photo capturing part of the library.  

I have done all the normal setup like for video recording (works fine), and changed the required setup for photo capture and setup 3 delegate methods as well.  

I am using [[PBJVision sharedInstance] capturePhoto]; on a button action to capture photo but none of the 3 delegates gets called: 

````
- (void)visionWillCapturePhoto:(PBJVision *)vision
{
}

- (void)visionDidCapturePhoto:(PBJVision *)vision
{
}

- (void)vision:(PBJVision *)vision capturedPhoto:(NSDictionary *)photoDict error:(NSError *)error
{
}
````

On the UI part, the UI/preview layer just gets stuck on captured image/frame. Basically, the app is not stuck and still works (I can back and use other buttons) but the preview layer just makes the image capture sound and gets stuck with displaying the captured image on it

**Comment by holahyunsik** [comment]
All 3 of them do get called.

My problem is that I cannot access to photoDict but all of the above do get called.
