### ISSUE TITLE
Unknown error occurred (-12785) when capturing video

### ISSUE THREAD

**Issue by bwhiteley** [piemonte/PBJVision#272]
Each time I start a video capture a UIAlertView appears:
"An unknown error occurred (-12785)"

Otherwise it all seems to work. 

Has anyone seen this? 

I'm using version 0.4.2.

![image](https://cloud.githubusercontent.com/assets/601312/9152516/30f27c8e-3de9-11e5-8c81-c520ef8c8d1d.png)

**Comment by misslester** [comment]
duplicate https://github.com/piemonte/PBJVision/issues/270
