### ISSUE TITLE
Regarding Background mode push and play video

### ISSUE THREAD

**Issue by pareshvasoya1** [piemonte/PBJVision#274]
Hi @piemonte 

I am working on Video application. I have integrated PBJVision lib to my project it is working fine in foreground but when I go to background mode it is end capturing. I want to integrate pause feature when go in background. I have latest pod installed on my Xcode project it has method for pause video capture I have tried using it but it does not works. So I want to know about pause feature implementation.

Thanks

**Comment by piemonte** [comment]
hi @pareshvasoya1 thanks for the inquiry. the proper solution is to do file appending. which we will do with the issue:

:paperclip: https://github.com/piemonte/PBJVision/issues/2
