### ISSUE TITLE
Camera lags for 2-5 seconds sometimes and stays black

### ISSUE THREAD

**Issue by mitchellporter** [piemonte/PBJVision#275]
Just wanted to see if anyone else is experiencing this. This is a very hard issue for me to reproduce, it seems to just pop up randomly from time to time, but sometimes when you go to use the camera the screen will stay black for 2-5 seconds before it can display the camera input.

Not a huge issue, but I've had some users complain to me about it. Not really sure how to go about fixing this though, especially since it seems to happen randomly.

Curious to see if anyone else is experiencing this.

Thanks.

**Comment by piemonte** [comment]
i believe this is a dup:

:paperclip: https://github.com/piemonte/PBJVision/issues/115
