### ISSUE TITLE
pauseVideoCapture and resumeVideoCapture bug when audioCaptureEnabled=NO

### ISSUE THREAD

**Issue by xuming120** [piemonte/PBJVision#276]
If audioCaptureEnabled=NO, the video data from AVCaptureVideoDataOutputSampleBufferDelegate can't be write when resumeVideoCapture. because _flags.interrupted can't set to NO when pauseVideoCapture. add  _flags.interrupted = NO can fixed this bug.
if (_flags.interrupted) {
        if (isVideo) {
            CFRelease(sampleBuffer);
            _flags.interrupted = NO;
            return;
        }

**Comment by piemonte** [comment]
thanks @xuming120 this is a known issue. 

:paperclip: https://github.com/piemonte/PBJVision/issues/178
