### ISSUE TITLE
Turn audio capture on/off during recording

### ISSUE THREAD

**Issue by ichents** [piemonte/PBJVision#277]
Hi,

I need to turn audio capture on/off during recording (according to input from user). Is there a way to do it? I couldn't make it work.. 

Do you have a solution for me?

Thanks!

**Comment by piemonte** [comment]
this is should be covered in:

:paperclip: https://github.com/piemonte/PBJVision/issues/178

**Comment by ichents** [comment]
Sorry, but i didn't understand it...

I start recording with:
        [[PBJVision sharedInstance] startVideoCapture];

Then, at some point i want to turn video's sound off. Tried using:
    [[PBJVision sharedInstance] setAudioCaptureEnabled:NO];
 
This did not turn the audio off.

Do you support turning audio on/off during video capture? if so, i'd love some code examples.

**Comment by ANTARESXXI** [comment]
Any update on this? How can we turn audio capture on/off during recording?
