### ISSUE TITLE
Save video session temporally 

### ISSUE THREAD

**Issue by chlebta** [piemonte/PBJVision#278]
Hello, I need to know how to save video session temporally, so when user after recording video push new view ( next view ) and then go back to recording video page instead of reseting video session user can continue recording on the previous video like in vine .

**Comment by piemonte** [comment]
yes, this is a great idea. we hope to update the code to support this with:

:paperclip: https://github.com/piemonte/PBJVision/issues/2

thanks for the note, there are some folk investing doing this soon
