### ISSUE TITLE
Output video is not cropped correctly

### ISSUE THREAD

**Issue by olivierlesnicki** [piemonte/PBJVision#279]
My preview layer is the full size of the iPhone 6 screen. However the video produced is of an aspect ratio slightly different and doesn't fill the screen.

**Comment by mackdaddy17** [comment]
I had the same problem and found a fix. It has to do with setting the AVCaptureSessionPreset. The default is set to AVCaptureSessionPresetPhoto in the _setupSession method around line 1116. For some reason calls to setCaptureSessionPreset does not actually change it. The method is ran but [_captureSession canSetSessionPreset:captureSessionPreset] returns NO. To fix this change the line sessionPreset = AVCaptureSessionPresetPhoto; where I previously mentioned to whatever preset you desire. AVCaptureSessionPresetHigh should work.

**Comment by piemonte** [comment]
thanks, we've got a bug tracking this

:paperclip: https://github.com/piemonte/PBJVision/issues/74
