### ISSUE TITLE
How can we save a photo and video to our Custom Folders

### ISSUE THREAD

**Issue by kunalgupta1593** [piemonte/PBJVision#281]
I am using PBJ Vision and willing to save the Photos and Videos to a totally different separate folder with my App name. as "XYZ Images" and "XYZ Videos". 
How can this be Implemented.?

**Comment by holahyunsik** [comment]
For pictures it's here -
- (void)vision:(PBJVision *)vision capturedPhoto:
.... NSString *albumName = @"PBJVision";  <- change this

**Comment by piemonte** [comment]
thanks @holahyunsik 

yep, just modify the sample project to fit your needs.

https://github.com/piemonte/PBJVision/blob/master/Project/Vision/PBJViewController.m#L598
