### ISSUE TITLE
If we set PBJVision the videoFrameRate property ,it can not work any more.

### ISSUE THREAD

**Issue by shiflymoon** [piemonte/PBJVision#285]
I just set [PBJVision sharedInstance].videoFrameRate = 20;  I find that  the follow code always return NO:

BOOL isReadyToRecord = ((!_flags.audioCaptureEnabled || _mediaWriter.isAudioReady) && _mediaWriter.isVideoReady);
    if (!isReadyToRecord) {
        CFRelease(sampleBuffer);
        return;
    }

And I just set  [PBJVision sharedInstance].videoFrameRate = 20 when begin record in the example.
such as:
- (void)_handleLongPressGestureRecognizer:(UIGestureRecognizer *)gestureRecognizer
{
    // PHOTO: uncomment to test photo capture
//    if (gestureRecognizer.state == UIGestureRecognizerStateBegan) {
//        [[PBJVision sharedInstance] capturePhoto];
//        return;
//    }

    switch (gestureRecognizer.state) {
      case UIGestureRecognizerStateBegan:
        {
            [PBJVision sharedInstance].videoFrameRate = 20;
            if (!_recording)
                [self _startCapture];
            else
                [self _resumeCapture];
            break;
        }
      case UIGestureRecognizerStateEnded:
      case UIGestureRecognizerStateCancelled:
      case UIGestureRecognizerStateFailed:
        {
            [self _pauseCapture];
            break;
        }
      default:
        break;
    }
}

**Comment by piemonte** [comment]
thanks @shiflymoon 

please see the solution here

:paperclip: https://github.com/piemonte/PBJVision/issues/302
