### ISSUE TITLE
CMTimeMakeWithSeconds(2.368 seconds, timescale 24): warning: error of -0.034 introduced due to very low timescale

### ISSUE THREAD

**Issue by holahyunsik** [piemonte/PBJVision#286]
Most times taken video still will be saved but there are times that don't.

Any way to fix this?

**Comment by rick711003** [comment]
I have same problem, plz help me !

**Comment by mg459046365** [comment]
I have same problem,too!

**Comment by TinyQ** [comment]
me too

**Comment by tettoffensive** [comment]
any update on this?

**Comment by holahyunsik** [comment]
Too many time-consuming issues. Got rid of this library altogether. My advice, don't use it.

**Comment by misslester** [comment]
should get fixed with https://github.com/piemonte/PBJVision/issues/2
