### ISSUE TITLE
*** -[AVAssetWriterInput markAsFinished] Cannot call method when status is 2

### ISSUE THREAD

**Issue by huofuxiang** [piemonte/PBJVision#289]
*** -[AVAssetWriterInput markAsFinished] Cannot call method when status is 2，
0   CoreFoundation                      0x00000001865602f4  + 160
	1   libobjc.A.dylib                     0x0000000197d8c0e4 objc_exception_throw + 60
	2   AVFoundation                        0x0000000184d712e0  + 0
	3   AVFoundation                        0x0000000184d6fe74  + 80
	4                                                0x100055f08  + 352008
	5                                                0x10013d39c + 1299356
	6   libdispatch.dylib                   0x00000001983dd994  + 24
	7   libdispatch.dylib                   0x00000001983dd954  + 16
	8   libdispatch.dylib                   0x00000001983e80a4  + 1448
	9   libdispatch.dylib                   0x00000001983e0a5c  + 132
	10  libdispatch.dylib                   0x00000001983ea318  + 720
	11  libdispatch.dylib                   0x00000001983ebc4c  + 108
	12  libsystem_pthread.dylib             0x00000001985bd22c _pthread_wqthread + 816
	13  libsystem_pthread.dylib             0x00000001985bcef0 start_wqthread + 4
)

**Comment by misslester** [comment]
timing issue with how the writer is setup. will be fixed with https://github.com/piemonte/PBJVision/issues/2
