### ISSUE TITLE
Higher Resolution Output

### ISSUE THREAD

**Issue by imack** [piemonte/PBJVision#29]
If I have a preview view at 320x320, is there a way I can get it to record at double the resolution? Vine and Instagram seem to generate videos at 600x600 and I'd like to have that kind of resolution for viewing on the web. Can't seem to find that anywhere.

Thanks! Love the library.

**Comment by mitchellporter** [comment]
@piemonte Would you mind sharing the default settings that were used to create "compression settings similar to Vine" like in your comment?

I've modified all of mine and it's producing extremely high quality video but the file sizes are very large.

**Comment by mitchellporter** [comment]
For anyone who's curious, here are my current settings for capturing the highest quality video:

    vision.cameraMode = PBJCameraModeVideo;
    vision.cameraOrientation = PBJCameraOrientationPortrait;
    vision.focusMode = PBJFocusModeContinuousAutoFocus;
    vision.outputFormat = PBJOutputFormatPreset;
    vision.captureSessionPreset = AVCaptureSessionPresetHigh;

The only problem is that a 4 minute video recorded with these settings will be around 100 MB which is ridiculous. I'm uploading these to an AWS S3 bucket and even on wifi the uploads feel pretty slow.

I really need to find a way to reduce the file size but still keep some quality.

Here are some code comments I left myself 3 weeks ago:

    // AVCaptureSessionPresetHigh w/ a lower bitrate of PBJVideoBitRate480x360 looks good
    // while they are recording, but then when you go to play it, it looks terrible eg. fuzzy
    // especially if moving the camera while recording.
