### ISSUE TITLE
Cannot remove an observer for the key path "currentDevice.flashAvailable

### ISSUE THREAD

**Issue by srinadhK** [piemonte/PBJVision#290]
Hi,
   App getting crash with following error.  *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Cannot remove an observer <PBJVision 0x17ea24d0> for the key path "currentDevice.flashAvailable" from <PBJVision 0x17ea24d0>, most likely because the value for the key "currentDevice" has changed without an appropriate KVO notification being sent. Check the KVO-compliance of the PBJVision class.'

**Comment by piemonte** [comment]
thanks for reporting.

:paperclip: https://github.com/piemonte/PBJVision/issues/189
