### ISSUE TITLE
PBJVisionDelegate callback in case of _sessionRuntimeErrored

### ISSUE THREAD

**Issue by sanielfishawy** [piemonte/PBJVision#292]
It would be useful to have a callback to the delegate in case of sessionRuntimeError. I don't see a way to do this. Please let me know if I am missing something.

Currently in case for example the mic is in use by a phone call when preview is started PBJVision will go into a loop of:

```objective-c
[self _destroyCamera];
if (_flags.previewRunning)
    [self startPreview];
```

It would be helpful for an app using PBJVision to at least know that an error is occurring.

If you think this would be useful to include in your pod I am happy to submit a pull request.

**Comment by misslester** [comment]
@sanielfishawy hi, yes, contributions welcome
