### ISSUE TITLE
Crash with gpus_ReturnNotPermittedKillClient when entering background in app that allows background processing.

### ISSUE THREAD

**Issue by sanielfishawy** [piemonte/PBJVision#294]
PBJVision uses EAGLContext for some processing. 

If PBJ Vision is included in a app that allows background processing the app will sometimes crash when moving to the background because PBJVision may make GL calls which is not allowed by the OS in the background.

What is the recommended approach for dealing with this?

**Comment by piemonte** [comment]
i need to add in support for backgrounding sometime:

:paperclip: https://github.com/piemonte/PBJVision/issues/2
