### ISSUE TITLE
maximumCaptureDuration is not precise

### ISSUE THREAD

**Issue by ataranlen** [piemonte/PBJVision#295]
I set up my sharedInstance of PBJVision with a maximumCaptureDuration as follows:
```
[[PBJVision sharedInstance] setMaximumCaptureDuration:CMTimeMakeWithSeconds(10.0f 600)];
```

The resulting PHAsset's duration is 10.025011337868481. (Another time it was 10.058344671201814, it varies)
This is causing a UIVideoEditorController's VideoMaximumDuration to trigger when set to 10.0f, requiring a fraction of a second to be trimmed off.

```
[videoEditor setVideoMaximumDuration:[YovoGlobalClass deviceMaxRecordingTime]];
```

**Comment by misslester** [comment]
thanks for reporting, duplicate issue for https://github.com/piemonte/PBJVision/issues/90
