### ISSUE TITLE
How to play the Landscape Video in the MpMovieplayer in Landscape mode.

### ISSUE THREAD

**Issue by ajay2c9** [piemonte/PBJVision#296]
I take a video in Landscape mode . i am playing the Video using MPMovieplayer in Landscape mode. the problem is video is playing in  another order. how to play the Landscape Video in the MPMovieplayer  Landscape mode .

Thank you

**Comment by Trupti15** [comment]
Hi Ajay , have you solved this issue?Please reply

**Comment by ajay2c9** [comment]
Hi Trupti. i am still working on issue.

**Comment by Trupti15** [comment]
Thanks a lot Ajay fir replying . please let me know if u r getting any
solution.

**Comment by ajay2c9** [comment]
ok

**Comment by piemonte** [comment]
:paperclip: https://github.com/piemonte/PBJVision/issues/84
