### ISSUE TITLE
Setting the frame for the preview layer results in incorrect frame settings

### ISSUE THREAD

**Issue by danipralea** [piemonte/PBJVision#301]
Hello and what an awesome work you've done with this library. I would like to thank you for all your hard work.

I integrated it into a Swift project and when I'm trying to set the frame of the preview layer, it results in an inconsistent frame:
![img_1678](https://cloud.githubusercontent.com/assets/768893/12699384/e9824efc-c7c1-11e5-93b0-bb771ea450a8.PNG)

I have this code:

``` swift
var _previewLayer: AVCaptureVideoPreviewLayer = PBJVision.sharedInstance().previewLayer
@IBOutlet weak var previewView: UIView! // this is the white view in the back

let bounds = self.previewView.layer.bounds
_previewLayer.videoGravity = AVLayerVideoGravityResizeAspectFill
_previewLayer.bounds = bounds
_previewLayer.position = CGPointMake(CGRectGetMidX(bounds), CGRectGetMidY(bounds))
previewView.layer.addSublayer(_previewLayer)
```

**Comment by imagine** [comment]
Especially since you're using Swift, you may want to switch to [NextLevel](https://github.com/NextLevel/NextLevel)
