### ISSUE TITLE
PBJFocusModeContinuousAutoFocus appears not to be working when the camera mode is set to PBJCameraModeVideo

### ISSUE THREAD

**Issue by sasojadrovski** [piemonte/PBJVision#306]
Hello @piemonte,

First of all let me thank you for the amazing work that you have done on this library! I have been using it on several projects now, and it still amazes me :)

For one of the projects I am using the library for video recording. Until now I have been using it only for recording videos with the Front camera, but now I need to be able to record videos using the back camera as well. I have implemented the camera switch, but when the switch occurs (while still in preview and not recording), the auto focus seems to stop working :( 

This is not the case with the PBJExposureModeContinuousAutoExposure - this one works as it should.

Could you please take a look at this one and check whether it is a small bug. Otherwise, please provide me some guidelines on how to implement the camera switch (while in preview) just to make sure that I am not doing anything wrong.

Thanks in advance!

**Comment by piemonte** [comment]
hey @sasojadrovski thanks for reaching out. bummer to hear about the bug, i'll mark this and try to help when i can or get a collaborator to help.

i'm involved with a contract so i'm unable to personally support updates. a friend of mine and i do have some more video libraries in the works which is getting a lot more attention, will share soon.

**Comment by GabeJacobs** [comment]
Would love an update on this!
