### ISSUE TITLE
Expose _captureSession.automaticallyConfiguresApplicationAudioSession property

### ISSUE THREAD

**Issue by CAMOBAP795** [piemonte/PBJVision#308]
**Problem**

I faced with case when I need mix micro audio with background audio (audio form iTunes player).

I have found [solution](http://stackoverflow.com/a/28026142/902217) to achieve this, one of step of this solution require

```
AVCaptureSession *session = [[AVCaptureSession alloc] init];
session.automaticallyConfiguresApplicationAudioSession = NO;
```

I noticed that `PBJVision` expose 'similar' property `_captureSession.usesApplicationAudioSession` so I think this isn't a big deal to add another one

**Proposed solution**

add `@property (nonatomic) BOOL automaticallyConfiguresApplicationAudioSession;` to `PBJVision` class (I can prepare a pull request if needed)

**Comment by CAMOBAP795** [comment]
Pull request ready https://github.com/piemonte/PBJVision/pull/312

**Comment by CAMOBAP795** [comment]
@piemonte may I know the reason why it wasn't accepted?

**Comment by piemonte** [comment]
sorry @camobap795 i thought it had been merged. can look at it for you tomorrow.

**Comment by piemonte** [comment]
it looks like it was merged in, is there another PR?

**Comment by CAMOBAP795** [comment]
@piemonte  yes you are right, sorry for misleading

**Comment by piemonte** [comment]
@camobap795 it is no problem, thanks for the contribution ✌️️
