### ISSUE TITLE
How do I implement an undo function as in instagram or vine?

### ISSUE THREAD

**Issue by ManholeGit** [piemonte/PBJVision#315]
First, Your code is very useful. Thanks. :)

My Solutions : 

Every time a touch event occurs, a new video file is created.
If Undo is tapped, I delete the last file.
In the final step, I merge all files that are available .
Do you think this is the best way? or have any other idea?

**Comment by shaohung001** [comment]
i meet a demand like this, and i have no idea to start with it...,some one help?

**Comment by piemonte** [comment]
I've got a new solution in the works for video, will update the README as well as some of the issues here when it's available.

**Comment by shaohung001** [comment]
i have a solution of deleting the video when user finishing capture,but it is data that i fetch it from sandBox.It is not the case...

**Comment by piemonte** [comment]
Hey @ManholeGit if you checkout my NextLevel project, it has the ability to undo and re-arrange video clips.

🌎 https://github.com/NextLevel/NextLevel
