### ISSUE TITLE
change device back and front delay badly

### ISSUE THREAD

**Issue by youxigit** [piemonte/PBJVision#317]
- (void)setCameraDevice
  {
  PBJVision *vision = [PBJVision sharedInstance];
  vision.cameraDevice = vision.cameraDevice == PBJCameraDeviceBack ? PBJCameraDeviceFront : PBJCameraDeviceBack;
  }
  delay more than 3S

**Comment by piemonte** [comment]
Hey @youxigit thanks for the note. i recommend checking out http://github.com/nextlevel/nextlevel

It's more resilient when it comes to switching devices.
