### ISSUE TITLE
iOS 10 issues

### ISSUE THREAD

**Issue by mrvitalya** [piemonte/PBJVision#325]
In iOS 10 PBJVision can't save video. All time i get error `CMTimeMakeWithSeconds(** seconds, timescale **): warning: error of ** introduced due to very low timescale`

Any help would be greatly appreciated.

**Comment by imagine** [comment]
That error isn't related to the ability to save video. You mean nothing happens, or the app crashes? Does your app's Info.plist have the [privacy for Photos enabled](http://stackoverflow.com/questions/39631256/request-permission-for-camera-and-library-in-ios-10-info-plist)?
