### ISSUE TITLE
Flip camera while recording causes audio sync issues   

### ISSUE THREAD

**Issue by AndresCanella** [piemonte/PBJVision#328]
When you are capturing video and flip the camera while still capturing. Audio will be chopped and become out of sync.

**Comment by piemonte** [comment]
Hey @AndresCanella thanks for the feedback. i'm aware of some of these issues which i've addressed in a new library:

http://github.com/NextLevel/NextLevel

Unfortunately, I don't have enough time to bring those logic changes back here at the moment. Hopefully in the future or if someone else wants to submit a PR.

**Comment by AndresCanella** [comment]
Thanks @piemonte ! 

Im dealing with this issue in our own library. We're adding flip functionality... All I need is a nudge in the right direction so I don't have to prototype different solutions to find the answer:)

I'll check out your new lib!!

**Comment by JoySeeDog** [comment]
@AndresCanella  hello，AndresCanella， I have also encountered the same problem，Can you tell me how to solve it?
