### ISSUE TITLE
- (void)captureOutput:(AVCaptureOutput *)captureOutput didOutputSampleBuffer:(CMSampleBufferRef)sampleBuffer fromConnection:(AVCaptureConnection *)connection

### ISSUE THREAD

**Issue by WANGNEWMAN** [piemonte/PBJVision#329]
iOS8.4 iphone 5c second time record video  - (void)captureOutput:(AVCaptureOutput *)captureOutput didOutputSampleBuffer:(CMSampleBufferRef)sampleBuffer fromConnection:(AVCaptureConnection *)connection      captureOutput never equal to _captureOutputAudio.It case record no data,because [_mediaWriter writeSampleBuffer:bufferToWrite withMediaTypeVideo:isVideo];
[_mediaWriter writeSampleBuffer:bufferToWrite withMediaTypeVideo:isVideo]; will never perform.
but it run normal first time

**Comment by WANGNEWMAN** [comment]
ios 9+ and ios 10+ is normal

**Comment by piemonte** [comment]
hey @WANGNEWMAN, thank you for the feedback. I'm not maintaining PBJVision for OS versions less than iOS 9. sorry about that, i just don't have the resources.

you are welcome to try older version releases, but the latest release is for iOS 9 and after.
