### ISSUE TITLE
Library create problem for ios 10

### ISSUE THREAD

**Issue by sachin19jan** [piemonte/PBJVision#330]
Hi,
   I am facing issue with library on ios 10, Earlier It works fine but now when I am trying to record video some time it's works some time not. Their is no log printed that's why I am not able to reach out exact issue please help me to debug the issue.

**Comment by piemonte** [comment]
📎 https://github.com/piemonte/PBJVision/issues/327

**Comment by piemonte** [comment]
@sachin19jan please make sure you're handling permissions properly too, by adding the appropriate camera, microphone, and photos keys to the Info.plist

**Comment by holgersindbaek** [comment]
I'm having a similar error:

https://github.com/piemonte/PBJVision/issues/345

Did you figure out what caused this?
