### ISSUE TITLE
Upgraded library not working

### ISSUE THREAD

**Issue by monish152** [piemonte/PBJVision#331]
Hi There, 

We are using PBJvision in our product. It was working fine with swift 1.0 version. Now we have updated it to swift 3.0 and app is giving inconsistent issues. Can you please help.

Thanks
Monish

**Comment by piemonte** [comment]
Hey Monish,

If you're developing in Swift, I recommend using my latest library:
⬆️ http://github.com/nextlevel/NextLevel

If you're seeing issues with PBJVision, can you describe what the issues are and what the actual problems are that you're encountering?
