### ISSUE TITLE
Frame loss at capturing start

### ISSUE THREAD

**Issue by Briahas** [piemonte/PBJVision#335]
Hi @piemonte, I've experience a subj problem almost in 90% cases. Do you have some solutions for this?

**Comment by piemonte** [comment]
hey @Briahas – if you're open to swift, i've started a new video project... it'll be some time before I bring that same logic back here.

http://github.com/NextLevel/NextLevel

**Comment by Briahas** [comment]
NextLevel require iOS10, but my app must support iOS9.

So I sticked to PBJVision
