### ISSUE TITLE
Deployment target

### ISSUE THREAD

**Issue by jardamach** [piemonte/PBJVision#337]
Hi there, 

I would like to ask what was the reason for increasing deployment target to iOS 9.0. Was it just to remove support of older versions of the iOS system? I am thinking about forking the library and setting deployment target back to iOS8.0 - are there any changes after deployment target change that are not buildable / might cause unwanted behavior on iOS8.0?

Thank you!

**Comment by piemonte** [comment]
hey @jardamach thanks for checking out the project. i try to keep most projects tested and supported on the last two OS releases for maintenance reasons. apologies, i don't have enough time to test and maintain changes on versions that go back more, especially when the install bases are much smaller.

You can use an earlier version of PBJVision, I believe 0.4.2 should go back.

If you're going to make a fork, I believe these were the only two commits I made for dropping iOS 8:

commit 86854e81377f4f26fefbb1c50bb7d33ace921c75
Author: patrick piemonte <piemonte@alumni.cmu.edu>
Date:   Tue Aug 9 22:59:53 2016 -0700

    update sample project for iOS 9
    bump podspec version

commit 441062c6adf8a16867f88f227c9032759b2dbde0
Author: patrick piemonte <piemonte@alumni.cmu.edu>
Date:   Tue Aug 9 22:20:42 2016 -0700

    update PBJVision to have a minimum version of iOS 9

**Comment by jardamach** [comment]
@piemonte Thank you for such a quick response. I really appreciate what you do and it's totally understandable the reason why you're keeping two latest versions instead of more.
