### ISSUE TITLE
PBJVisionUtilities convertToPointOfInterestFromViewCoordinates changes

### ISSUE THREAD

**Issue by relatedcode** [piemonte/PBJVision#340]

**Comment by relatedcode** [comment]
@piemonte Hi there,

As far as I see PBJVisionUtilities convertToPointOfInterestFromViewCoordinates is no longer part of the code. What is the best practice to manage the situation below now.

Thanks!

KZ

**Comment by relatedcode** [comment]
```
- (void)handleTapGesterRecognizer:(UIGestureRecognizer *)gestureRecognizer
{
	CGPoint tapPoint = [gestureRecognizer locationInView:viewPreview];
	CGPoint adjustPoint = [PBJVisionUtilities convertToPointOfInterestFromViewCoordinates:tapPoint inFrame:viewPreview.frame];
	[[PBJVision sharedInstance] focusExposeAndAdjustWhiteBalanceAtAdjustedPoint:adjustPoint];
}
```

**Comment by piemonte** [comment]
hey @relatedcode thanks for the inquiry. iOS provides a function to do this for you, so i thought it'd be best for folks to use the system code vs my own. There was a few cases I didn't handle.

https://developer.apple.com/reference/avfoundation/avcapturevideopreviewlayer/1623497-capturedevicepointofinterestforp

If it doesn't work as well for you, we can always bring it back, let me know how it goes. This was the commit:

7a69e730a96959586e3e19f29a24ede5630021c9

**Comment by relatedcode** [comment]
@piemonte Thanks man! :)
