### ISSUE TITLE
Text in capture video

### ISSUE THREAD

**Issue by kleruk** [piemonte/PBJVision#343]
We need to record the text on video. For example, the date and time. I tried to do this using the method of the delegate
` - (void)vision:(PBJVision *)vision didCaptureVideoSampleBuffer:(CMSampleBufferRef)sampleBuffer`

` CVPixelBufferRef pixelBuffer = CMSampleBufferGetImageBuffer(sampleBuffer);
    
    CVPixelBufferLockBaseAddress( pixelBuffer, 0 );
    
    CIContext *ciContext = [CIContext contextWithEAGLContext:[PBJVision sharedInstance].context options:@{kCIContextWorkingColorSpace : [NSNull null]} ];
    
    NSString *string = @"LOADING TEXT";
    
    NSDictionary *attributes = @{NSFontAttributeName            : [UIFont systemFontOfSize:20],
                                 NSForegroundColorAttributeName : [UIColor whiteColor],
                                 NSBackgroundColorAttributeName : [UIColor blackColor]};
    
    UIImage *image = [UIImage imageFromString:string
                                   attributes:attributes
                                         size:CGSizeMake(320, 100)];
    
    CIImage *filteredImage = [[CIImage alloc] initWithCGImage:image.CGImage];
    
    [ciContext render:filteredImage toCVPixelBuffer:pixelBuffer bounds:[filteredImage extent] colorSpace:CGColorSpaceCreateDeviceRGB()];
    
    CVPixelBufferUnlockBaseAddress(pixelBuffer, 0); `

but it does not work. 
Would you like to add this opportunity?

**Comment by imagine** [comment]
Try modifying the buffer in the earlier delegate vision:didReceiveVideoSampleBuffer:
Your code will need to be super performant, so maybe cache that UIImage creation.

**Comment by kleruk** [comment]
imagine, thanks for your reply.
I would like to be able to do this with the help of a delegate, because it is not possible to modify it since it is used with Pods

**Comment by imagine** [comment]
Oh the delegate I posted may only exist in my fork! You can easily reference a GitHub branch in your Podfile, for what it’s worth.

At some point I’ll make a pull request here for my modification. The naming or commenting would need to make the performance concerns very explicit.
