### ISSUE TITLE
Capture from both cameras simultaneously

### ISSUE THREAD

**Issue by cahernanz** [piemonte/PBJVision#344]
Hi developers. As I said in the title of this post. I want to capture from both cameras at the same time. I know that it is not possible on Iphone devices but i tried to switch cameras very quickly. Iphone waste a lot of time switching between cameras. I want to know if PBJVision could switch cameras more efficiently or record simultaneously from them. The ideal y to show in preview back camera and record frames from it, and record frames in front camera at the same time without previewing it and do not lose the front preview.

Thanks in advance.

**Comment by piemonte** [comment]
this is not supported on iOS itself
