### ISSUE TITLE
Delay/lag when starting a recording in landscape mode

### ISSUE THREAD

**Issue by rickwaalders** [piemonte/PBJVision#35]
First of all thanks a lot for PBJVision. It has really helped me speed up the development of my app.

When my app opens, it starts in Portrait mode. Turning the iPhone sideways sets it to Landscape mode.
The problem I have is that when it's turned to Landscape, starting a recording makes the app 'freeze' for a short moment. After the freeze it starts recording like normal.
When I open the app and just start recording in Portrait mode I don't experience the freeze.

The only thing that is changed before the freeze happens is this:

```
    [vision setCameraOrientation:cameraOrientation];
    [vision setOutputFormat:PBJOutputFormatWidescreen];
    [vision setFocusMode:PBJFocusModeContinuousAutoFocus];
```

Chaning the OutputFormat to PBJOutputFormatWidescreen causes the freeze when a new recording is started. If I remove that line it records without the freeze.

Is this a known problem? Or might I be doing something wrong?

**Comment by ancheng1114** [comment]
hey , @rickwaalders 
Could you solve that problem ?
