### ISSUE TITLE
add better support for single core devices

### ISSUE THREAD

**Issue by jai** [piemonte/PBJVision#88]
Hey - so a bit new to video on iOS - I'm trying to update a UIProgressView when recording but finding that it's stealing the main thread from the capture session. The shorter the update interval of the UIProgressView (either using NSTimer or GCD), the choppier the video is.

Is AVCaptureSession not thread safe by default, or just this particular implementation? I notice other apps like Vine have no problem updating the UI while video is recording so either they're using something like CADisplayLink to update the UI or there's a way to record video off the main thread?

**Comment by piemonte** [comment]
going to close this, not something we'll support at this time. let me know if it's important otherwise.
