### ISSUE TITLE
add  an undo button

### ISSUE THREAD

**Issue by ghost** [piemonte/PBJVision#9]
great work on this by the way!

**Comment by shaohung001** [comment]
does anyone solve this problem?i don't know how to start,can anyone send a help ?very thanks.

**Comment by piemonte** [comment]
hey @ghost and all, i started a swift version of this project that properly handling editing a recorded session and undo:

http://github.com/nextlevel/nextlevel

just posted it a few days ago, so some  functionality needs a little love.
