### ISSUE TITLE
capturedVideoSeconds is not accurate

### ISSUE THREAD

**Issue by silviucpp** [piemonte/PBJVision#90]
At the end of the movie if you compare the duration from capturedVideoSeconds with the one returned by the following function they are always different. Sometime the difference is pretty big.

I guess the above function is the most accurate method to get the movie duration.

<pre>
-(Float64) GetDuration:(NSURL*)path
{
    NSDictionary *options = @{AVURLAssetPreferPreciseDurationAndTimingKey:@YES};
    
    AVURLAsset *assetClip = [AVURLAsset URLAssetWithURL:path options:options];
    NSArray *clipVideoTracks = [assetClip tracksWithMediaType:AVMediaTypeVideo];
    
    if(clipVideoTracks.count == 0)
        return 0;
   
    AVAssetTrack *videoTrack = clipVideoTracks[0];
    return CMTimeGetSeconds(videoTrack.timeRange.duration);
}
</pre>

**Comment by tar500** [comment]
#215

**Comment by piemonte** [comment]
if i have some time, i'd like to add the "movie" mode, which is single clip recording only. this would provide a more accurate means for capture seconds, i believe.
