### ISSUE TITLE
UIImagePickerController and PBVision don't work together.

### ISSUE THREAD

**Issue by tdunham02** [piemonte/PBJVision#95]
I use UIImagePickerController to take pictures, and then open PBJVision modally to take video, after opening the uiimagepicker controller, PBJVision doesn't record video and the progress methods aren't called.

**Comment by holahyunsik** [comment]
omg.. thank you so much @tdunham02  Ive been having the same problem with my other custom avfoundation based camera and your solution perfectly helped.
its not just uiimagepickercontroller. PBJ def doesn't work once another camera is presented it seems.
